services:
  postgres:
    image: postgres:16
    container_name: digital_wallet_postgres
    environment:
      POSTGRES_DB: digital_wallet_reviews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: